### ISSUE TITLE
Error in guides$setup

### ISSUE THREAD

**Issue by ManishaSingh12560** [tylerbhampton/budykoR#1]
Hello Sir, I have been trying to run this package but I am getting stuck due to this error. Can you please help me?
> blackBC
Error: object 'blackBC' not found
> blankBC
Error in guides$setup(scales, aesthetics, default = params$guide_default %||%  : 
  attempt to apply non-function
> blankBC+geom_point(data=testdata)+coord_cartesian(xlim=c(0,5))
Error in guides$setup(scales, aesthetics, default = params$guide_default %||%  : 
  attempt to apply non-function
> ogbudyko=budyko_sim()
> blankBC+geom_line(data=ogbudyko)+coord_cartesian(xlim=c(0,5))
Error in guides$setup(scales, aesthetics, default = params$guide_default %||%  : 
  attempt to apply non-function
> blankBC+
+     geom_line(data=ogbudyko)+
+     geom_point(data=testdata)+
+     coord_cartesian(xlim=c(0,5))
Error in guides$setup(scales, aesthetics, default = params$guide_default %||%  : 
  attempt to apply non-function

**Comment by tylerbhampton** [comment]
#6d8a5af 
I fixed the blankBC data file that comes with the package. Testing on my end indicates the issue is fixed. I was getting the same error messages as you beforehand.
